swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: price-api-controller
    description: Price Api Controller
paths:
  '/v2/providers/avocado/apis/api/v1/vendors/{vendor}/prices':
    put:
      tags:
        - price-api-controller
      summary: update
      operationId: updateUsingPUT_3
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization
          required: true
          type: string
        - name: vendor
          in: path
          description: vendor
          required: true
          type: string
        - in: body
          name: pricelist
          description: pricelist
          required: true
          schema:
            $ref: '#/definitions/PriceList'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Price:
    type: object
    properties:
      currency:
        type: string
        enum:
          - USD
          - KRW
      discountedPrice:
        type: number
        format: double
      msrp:
        type: number
        format: double
      standardPrice:
        type: number
        format: double
    title: Price
  PriceList:
    type: object
    properties:
      prices:
        type: object
        additionalProperties:
          $ref: '#/definitions/Price'
    title: PriceList
  Response:
    type: object
    properties:
      success:
        type: boolean
    title: Response